### ISSUE TITLE
Cannot find module 'nanoid/non-secure' after upgrade to 4.1.0

### ISSUE THREAD

**Issue by adamdehaven** [Justineo/vue-awesome#178]
After upgrading vue-awesome to version `4.1.0` from `4.0.2` (noticing that `nanoid` dependency was removed) when running my project and serving over localhost, I receive an uncaught error:

``` javascript
Uncaught Error: Cannot find module 'nanoid/non-secure'
    at webpackMissingModule (cjs.js?!./node_modul…=script&lang=js&:23)
    at eval (cjs.js?!./node_modul…=script&lang=js&:23)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./node_modules/vue-awesome/components/Icon.vue?vue&type=script&lang=js& (app.js:2921)
    at __webpack_require__ (app.js:833)
    at fn (app.js:130)
    at eval (Icon.vue?e26c:1)
    at Module../node_modules/vue-awesome/components/Icon.vue?vue&type=script&lang=js& (app.js:8755)
    at __webpack_require__ (app.js:833)
    at fn (app.js:130)
    at eval (Icon.vue?17c7:1)
```

Also, I noticed that while the npm version is bumped with releases, the [GitHub releases](https://github.com/Justineo/vue-awesome/releases) are not updated and currently sit stale at `v3.1.0`.

**Comment by Justineo** [comment]
Have you tried clearing your build cache? eg. `node_modules/.cache`.

**Comment by adamdehaven** [comment]
@Justineo I just ran `npm cache clear --force` and still see the same error.

**Comment by adamdehaven** [comment]
Tried removing all `node_modules` and that did the trick with a clean install. Good work - love this repo :tada"
